---
abstract: 'Module to search a keyword in a FreeDB-Database.'
author:
  - 'Henning Mersch <hm@mystical.de>, Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-FreeDB
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 1.32
  Test::More: 0.45
version: 0.79
